export const guests = [
  {
    name: "Milshan Fernando",
    id: "980153568v",
    nationality: "Sri Lankan",
    email: "fdomilshan@gmail.com",
    phone: "0521420108",
    proof: [],
  },
  {
    name: "Ahamed Zubair",
    id: "784-1987-1234567-1", // Emirates ID
    nationality: "UAE",
    email: "zubair.ah87@gmail.com",
    phone: "0583217789",
    proof: [],
  },
  {
    name: "Jessica Thompson",
    id: "PP98765432", // Passport
    nationality: "British",
    email: "jess.thompson@mail.com",
    phone: "0508892345",
    proof: [],
  },
  {
    name: "Sajith Perera",
    id: "784-1992-7654321-4", // Emirates ID
    nationality: "Sri Lankan",
    email: "sajith.p@gmail.com",
    phone: "0564421102",
    proof: [],
  },
  {
    name: "Maria Gonzales",
    id: "P-AE34566789", // Passport
    nationality: "Filipino",
    email: "maria.gonzales@example.com",
    phone: "0529984412",
    proof: [],
  },
  {
    name: "Chen Wei",
    id: "E78455667788", // Passport/Foreign ID
    nationality: "Chinese",
    email: "chenwei.cn@gmail.com",
    phone: "0557132210",
    proof: [],
  },
];

// All reservations (assigned + upcoming), upcoming reservations have room: null
export const allocatedRooms = [
  // Already assigned rooms
  {
    propertyId: 1,
    room: 101,
    type: "Single",
    guestName: "John Doe",
    guestId: "A123456",
    checkIn: "2025-12-01",
    checkOut: "2025-12-05",
    dueAmount: 100 * 4,
    status: "checkedIn",
  },
  {
    propertyId: 1,
    room: 102,
    type: "Double",
    guestName: "Jane Smith",
    guestId: "B654321",
    checkIn: "2025-12-02",
    checkOut: "2025-12-06",
    dueAmount: 150 * 4,
    status: "checkedIn",
  },
  {
    propertyId: 2,
    room: 106,
    type: "Single",
    guestName: "Maria Lopez",
    guestId: "D345678",
    checkIn: "2025-12-02",
    checkOut: "2025-12-06",
    dueAmount: 300 * 4,
    status: "checkedIn",
  },

  // Upcoming reservations (room not yet assigned)
  {
    propertyId: 1,
    room: null,
    type: "Single",
    guestName: "Liam Walker",
    guestId: "K123456",
    checkIn: "2025-12-10",
    checkOut: "2025-12-12",
    dueAmount: 100 * 2,
    status: "notCheckedIn",
  },
  {
    propertyId: 2,
    room: null,
    type: "Single",
    guestName: "Noah Johnson",
    guestId: "M789012",
    checkIn: "2025-12-12",
    checkOut: "2025-12-16",
    dueAmount: 300 * 4,
    status: "notCheckedIn",
  },
  {
    propertyId: 3,
    room: null,
    type: "Double",
    guestName: "James Brown",
    guestId: "O901234",
    checkIn: "2025-12-14",
    checkOut: "2025-12-18",
    dueAmount: 150 * 4,
    status: "notCheckedIn",
  },
];

// All rooms
export const rooms = [
  {
    roomNumber: 101,
    type: "Single",
    status: "Occupied",
    price: 100,
    cleaningStatus: "Clean",
    allocatedGuest: "John Doe",
    guestId: "A123456",
    bookFrom: "Booking.com",
    fromDate: "2025-12-01",
    toDate: "2025-12-05",
  },
  {
    roomNumber: 102,
    type: "Double",
    status: "Occupied",
    price: 150,
    cleaningStatus: "Dirty",
    allocatedGuest: "Jane Smith",
    guestId: "B654321",
    bookFrom: "Agoda",
    fromDate: "2025-12-02",
    toDate: "2025-12-06",
  },
  {
    roomNumber: 103,
    type: "Single",
    status: "Available",
    price: 100,
    cleaningStatus: "Clean",
    allocatedGuest: null,
    guestId: null,
    bookFrom: null,
    fromDate: null,
    toDate: null,
  },
  {
    roomNumber: 104,
    type: "Single",
    status: "Available",
    price: 300,
    cleaningStatus: "Clean",
    allocatedGuest: null,
    guestId: null,
    bookFrom: null,
    fromDate: null,
    toDate: null,
  },
  {
    roomNumber: 105,
    type: "Double",
    status: "Available",
    price: 150,
    cleaningStatus: "Clean",
    allocatedGuest: null,
    guestId: null,
    bookFrom: null,
    fromDate: null,
    toDate: null,
  },
  {
    roomNumber: 106,
    type: "Single",
    status: "Occupied",
    price: 300,
    cleaningStatus: "Dirty",
    allocatedGuest: "Maria Lopez",
    guestId: "D345678",
    bookFrom: "Walk-in",
    fromDate: "2025-12-02",
    toDate: "2025-12-06",
  },
  {
    roomNumber: 107,
    type: "Single",
    status: "Available",
    price: 100,
    cleaningStatus: "Clean",
    allocatedGuest: null,
    guestId: null,
    bookFrom: null,
    fromDate: null,
    toDate: null,
  },
  {
    roomNumber: 108,
    type: "Double",
    status: "Available",
    price: 150,
    cleaningStatus: "Clean",
    allocatedGuest: null,
    guestId: null,
    bookFrom: null,
    fromDate: null,
    toDate: null,
  },
];
